//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::configs::Entity as Configs;
pub use super::groups::Entity as Groups;
pub use super::templates::Entity as Templates;
pub use super::users::Entity as Users;
