//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::configs::Entity as Configs;
pub use super::groups::Entity as Groups;
pub use super::projects::Entity as Projects;
pub use super::templates::Entity as Templates;
pub use super::users::Entity as Users;
